# Generated by Django 5.2.16 on 2026-07-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="chunk_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_model",
            field=models.CharField(
                blank=True, default="text-embedding-ada-002", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="embedding_status",
            field=models.CharField(
                blank=True, default="PENDING", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="page_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="processing_duration",
            field=models.FloatField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="vector_database_status",
            field=models.CharField(
                blank=True, default="PENDING", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("UPLOADING", "Uploading"),
                    ("EXTRACTING", "Extracting"),
                    ("CHUNKING", "Chunking"),
                    ("EMBEDDING", "Embedding"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="UPLOADING",
                max_length=20,
            ),
        ),
    ]
